name: ddm_projeto_final
description: "Gestor Acadêmico Academic Connect."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Essencial para i18n e Datas
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2 # Ou 0.19.0 se estiver dando conflito

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1
  
  # Pacotes do App
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  flutter_nfc_kit: ^3.6.0
  flutter_tts: ^4.0.2
  file_picker: ^8.0.7
  url_launcher: ^6.3.0
  http: ^1.2.1
  xml: ^6.5.0
  shared_preferences: ^2.2.3
  dots_indicator: ^3.0.0

  # ANOTAÇÕES DO WIDGETBOOK
  # Este é o único que fica aqui
  widgetbook_annotation: ^3.1.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # PACOTES DE GERAÇÃO DE CÓDIGO
  build_runner: ^2.4.10
  widgetbook_generator: ^3.6.0

  # PACOTE PRINCIPAL DO WIDGETBOOK
  # (Removido das dependencies normais)
  widgetbook: ^3.13.0

flutter:
  uses-material-design: true